---
project_name: rtz-server

release:
  extra_files:
    - glob: ./LICENSE
  github:
    owner: USA-RedDragon
    name: "{{ .ProjectName }}"

dockers:
  - image_templates:
      - "ghcr.io/usa-reddragon/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/usa-reddragon/{{ .ProjectName }}:v{{ .Major }}-amd64"
      - "ghcr.io/usa-reddragon/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/usa-reddragon/{{ .ProjectName }}:latest-amd64"
    use: buildx
    goarch: amd64
    extra_files:
      - hack/passwd
      - hack/group
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.url=https://github.com/USA-RedDragon/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/USA-RedDragon/{{ .ProjectName }}
      - "--platform=linux/amd64"

docker_manifests:
  - name_template: "ghcr.io/usa-reddragon/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/usa-reddragon/{{ .ProjectName }}:{{ .Tag }}-amd64"
  - name_template: "ghcr.io/usa-reddragon/{{ .ProjectName }}:v{{ .Major }}"
    image_templates:
      - "ghcr.io/usa-reddragon/{{ .ProjectName }}:v{{ .Major }}-amd64"
  - name_template: "ghcr.io/usa-reddragon/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/usa-reddragon/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
  - name_template: "ghcr.io/usa-reddragon/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/usa-reddragon/{{ .ProjectName }}:latest-amd64"

builds:
  - main: .
    binary: "{{ .ProjectName }}"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
    flags:
      - -trimpath

milestones:
  - close: true
